version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  backend:
    build:
      context: ../fullstackbackend
      dockerfile: Dockerfile.backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fullstack
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: C:/Users/josip/Desktop/fullstack-front
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend